shared constraints and Picklist Constraints
rossvideo/Catena pull request #232
Opened 2024-08-11 23:50 UTC by Isaac-Robert-Ross

Shared constraints are now supported in the json schema through ref_oid along with the codegen. 
Picklist Constraints are now implemented.

Additional note - we lost type checking in the json schema since each type would check its own special constraint directly and this was not able to have a ref_oid without a lot of code duplication (adding the oneOf to each constraint) so for now I just switched it to the general constraint reference. maybe think of a way to add constraint type checking back?

Concern to think about - how to add the shared constraints to the global constraints map in the gen'd code.

2024-08-12 00:05 UTC, Isaac-Robert-Ross commented
also updated the lite UML to reflect current design of constraints [see here](https://lucid.app/lucidchart/f8e5c336-3c28-4f45-9844-6f8f8cb4d1bc/edit?invitationId=inv_4a6be56a-bf42-4a9f-ab54-262174f9b14c&page=RtlNJyFC5H4j#)

2024-08-12 14:42 UTC, mejohnnaylor requested changes
see issue #234

2024-08-16 18:45 UTC, mejohnnaylor approved these changes

2024-08-22 14:08 UTC, Isaac-Robert-Ross commented
pr merge on hold in favour of redoing changes with new codegen structure

2024-08-22 14:08 UTC, closed without merging

2024-08-22 14:10 UTC, Isaac-Robert-Ross commented
work is being done on branch feat-#211-ipr