Changed License to BSD 3
rossvideo/Catena pull request #256
Opened 2024-09-16 22:52 UTC by BeanJ4m

2024-09-19 13:06 UTC, johndanenRV requested changes
This looks good so far, but you also need to update the license in the C++ files and the cmake  files.

2024-09-20 21:35 UTC, BeanJ4m reviewed
Updated the License in the CPP files and CMake

2024-09-23 14:22 UTC, johndanenRV requested changes

2024-09-23 14:22 UTC, johndanenRV commented on sdks/cpp/common/include/ReflectionMacros.h
>  #pragma once
Move pragma once to line 1 before license to make style consistent with other files

2024-09-24 17:36 UTC, johndanenRV approved these changes

2024-09-26 18:42 UTC, merged