Feat-#268-bm
rossvideo/Catena pull request #294
Opened 2024-11-05 21:48 UTC by BeanJ4m

Issue #268

Added Menus support.
CodeGen supports menus.

2024-11-06 15:10 UTC, johndanenRV requested changes

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/common/include/IMenu.h
> +    // virtual void fromProto(const catena::Menu& menu) = 0;
Remove commented code

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/common/include/IMenuGroup.h
> +//
remove empty comment

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/common/include/IMenuGroup.h
> +    // virtual void fromProto(const catena::MenuGroup& menuGroup) = 0;
remove commented code

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/connections/gRPC/examples/use_menus/CMakeLists.txt
> +#
This comment is wrong

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/connections/gRPC/examples/use_menus/device.use_menus.json.cpp
> +// This file was auto-generated. Do not modify by hand.
This file should be deleted

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/connections/gRPC/examples/use_menus/device.use_menus.json.h
> +// This file was auto-generated. Do not modify by hand.
This file should be deleted

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/connections/gRPC/examples/use_menus/use_menus.cpp
> + * @file status_update.cpp
Comment is incorrect

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/connections/gRPC/src/ServiceImpl.cpp
> +            serializer_ = dm_.getComponentSerializer(clientScopes_, false); // select the shallow copy option
You need to update Device::getComponentSerializer to send menus. Once that is done, change the argument back to true a make sure the menus are properly streamed by DeviceRequest. I can give you some help here if needed.

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/lite/include/Menu.h
> +class Menu;  // forward declaration
Forward declaration not needed

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/lite/include/Menu.h
> +class MenuGroup;
Move this so that the same namespace isn't being used twice here

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/lite/include/Menu.h
> +    // void fromProto(const ::catena::Menu& menu) override;
remove commented code

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/lite/include/MenuGroup.h
> +    // void fromProto(const ::catena::MenuGroup& menuGroup) override;
Remove commented code

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/lite/src/Menu.cpp
> +// }
Remove commented code

2024-11-06 15:10 UTC, johndanenRV commented on sdks/cpp/lite/src/MenuGroup.cpp
> +// }
Remove commented code

2024-11-06 15:10 UTC, johndanenRV commented on tools/codegen/cpp/cppgen.js
> +
Reformat this so that it is not such a long line

2024-11-06 15:10 UTC, johndanenRV commented on tools/codegen/cpp/cppgen.js
> +      }
same thing here

2024-11-06 15:10 UTC, johndanenRV commented on tools/codegen/cpp/cppgen.js
> +
Remove commented code

2024-11-11 20:43 UTC, BeanJ4m commented on tools/codegen/cpp/cppgen.js
> +
Not sure if I can make it shorter

2024-11-19 20:50 UTC, johndanenRV submitted a review, later dismissed

2024-11-20 13:59 UTC, johndanenRV approved these changes

2024-11-22 21:19 UTC, merged